ATC streams:
  San Francisco (KSFO): https://d.liveatc.net/ksfo_gnd2
  New York JFK (KJFK): http://d.liveatc.net/kjfk_arinc
  Los Angeles (KLAX): https://d.liveatc.net/klax4n_atis_arr

Spotify playlists: 
  ATC curated: https://open.spotify.com/embed/playlist/5PMoeSrcXv4OrURJi48z9c
  Lo-fi chill: https://open.spotify.com/embed/playlist/37i9dQZF1DXdbXrPNafg9d
  Synthwave: https://open.spotify.com/embed/playlist/37i9dQZF1DX8tZsk68tuDw
