Spotify playlists:
  ATC curated: https://open.spotify.com/embed/playlist/5PMoeSrcXv4OrURJi48z9c
  Lo-fi chill: https://open.spotify.com/embed/playlist/37i9dQZF1DXdbXrPNafg9d
  Synthwave: https://open.spotify.com/embed/playlist/37i9dQZF1DX8tZsk68tuDw
  MS 2025: https://open.spotify.com/embed/playlist/6JtaNQ5MGxGVjU6DPCIXhz

ATC streams:
  Winnipeg (YWG): https://d.liveatc.net/cywg2_misc2
  San Francisco (SFO): https://d.liveatc.net/ksfo_twr
  New York JFK (JFK): https://d.liveatc.net/kjfk_co
  Los Angeles (LAX): https://d.liveatc.net/klax4n_atis_arr
  Newark (EWR): https://d.liveatc.net/kewr_gnd_pri
  Ottowa (YOW): https://d.liveatc.net/cyow3
  Chicago (ORD): https://d.liveatc.net/kord1n2_app_133625
  
### INTERNAL
Spotify client ID: "ffcdebabc2c04f95b0bf38e6b8da1e32"
Redirect URI: "http://127.0.0.1:8111"
GSheets key: "resources/gsheets_credentials.json"
Sheet ID: "13T00qQMSwqEheqJNO3j7ofbBo1D4WJ5l8bZuGmyPbCo"
Update interval (min.): 5
