ATC streams:
  Winnipeg (YWG): http://d.liveatc.net/cywg2_misc2
  San Francisco (SFO): https://d.liveatc.net/ksfo_twr
  New York JFK (JFK): http://d.liveatc.net/kjfk_co
  Los Angeles (LAX): https://d.liveatc.net/klax4n_atis_arr
  Newark (EWR): https://d.liveatc.net/kewr_gnd_pri

Spotify playlists: 
  ATC curated: https://open.spotify.com/embed/playlist/5PMoeSrcXv4OrURJi48z9c
  Lo-fi chill: https://open.spotify.com/embed/playlist/37i9dQZF1DXdbXrPNafg9d
  Synthwave: https://open.spotify.com/embed/playlist/37i9dQZF1DX8tZsk68tuDw
