meta: 
  name: chill atc
  link:
    github: https://github.com/mayasheth/chill_atc

color:
  palette:
    near_black: "#011b29"
    deep_blue: "#032334"
    pale_gray: "#DFE0EC"
    teal: "#398aa8"
    powder_blue: "#a9c5db"
    canary_yellow: "#f0de5e"
    soft_red: "#e74c3c"
    light_ocean: "#90e0ef"
    pale_ocean: "#caf0f8"
    spotify_green: "#1DB954"
    light_green: "#B4E68C"
    pale_green: "#D9F19A"
    
    black: deep_blue
    white: pale_gray

  foreground: white
  background: black
  primary: light_ocean # slider
  secondary: light_ocean # buttons
  success: spotify_green
  info: powder_blue
  warning: canary_yellow
  danger: soft_red

typography:
  # Declare all fonts to be downloaded from Google.
  fonts:
    - family: Montserrat
      source: google
    - family: Schibsted Grotesk
      source: google
    - family: Inconsolata
      source: google
      
  # Define how the fonts are used.
  base:
    family: Montserrat
    weight: 300
    color: pale_ocean
  headings:
    family: Schibsted Grotesk
    weight: 450
    color: pale_gray
  monospace:
    family: Inconsolata


defaults:
  bootstrap: 
    defaults:
      container-max-width: 600px
