meta: 
  name: chill atc
  link:
    github: https://github.com/mayasheth/chill_atc

color:
  palette:
    darkest_blue: "#011b29"
    deep_blue: "#032334"
    pale_gray: "#DFE0EC"
    teal: "#398aa8"
    powder_blue: "#a9c5db"
    canary_yellow: "#f0de5e"
    soft_red: "#e74c3c"
    light_ocean: "#90e0ef"
    pale_ocean: "#caf0f8"
    spotify_green: "#1DB954"
    light_green: "#B4E68C"
    pale_green: "#D9F19A"

    background: deep_blue
    foreground: pale_gray
    card_background: darkest_blue
    primary: pale_ocean
    secondary: light_ocean
    tertiary: teal

typography:
  # Declare all fonts to be downloaded from Google.
  fonts:
    - family: Montserrat
      source: google
    - family: Schibsted Grotesk
      source: google
    - family: Inconsolata
      source: google
      
  # Define how the fonts are used.
  base:
    family: Montserrat
  headings:
    family: Schibsted Grotesk
  monospace:
    family: Inconsolata
